import Head from 'next/head';
import Image from 'next/image';
import styles from '@/styles/Home.module.css';
import { use, useEffect, useState } from 'react';

export default function Home() {
  const [userName, setUserName] = useState('');
  const [userName2, setUserName2] = useState('');

  // 常見的 api 使用方式
  useEffect(() => {
    fetch('http://localhost:3001/test')
      .then((res) => res.json())
      .then((data) => setUserName(data.name))
      .catch((error) => console.error('Error fetching data: ', error));
  }, []);

  useEffect(() => {
    fetch('/api/test')
      .then((res) => res.json())
      .then((data) => setUserName2(data.name))
      .catch((error) => console.error('Error fetching data: ', error));

  }, [userName]);

  return (
    <>
      <Head>
        <title>Welcome to Next.js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.page}>
        <main className={styles.main}>
          <h1>哈囉, {userName}!</h1>
          <h1>哈囉, {userName2}!</h1>
          
          <Image src="/next.svg" alt="Next.js logo" width={180} height={38} priority />
        </main>
      </div>
    </>
  );
}

